var AllPhrases ={"list":[
        "synergy",
        "Hardware Issues",
        "Technical Debt",
        "Buy-in",
        "Low-hanging fruit",
        "pushback",
        "take the lead",
        "value-add",
        "Mac's are better",
        "paradigm",
        "Data Drivin",
        "Win WIn",
        "ROI",
        "Data Driven",
        "Ballpark (estimate)",
        "next gen",
        "customer-focused",
        "manage expectations",
        "scalable",
        "deliverable",
        "actionable",
        "move forward",
        "Version 10 :(",
        "Teirs",
        "Cloud",
        "manage Branding"
]}