var AllPhrases ={"list":[
        "synergy",
        "Hardware Issues",
        "Technical Debt",
        "Buy-in",
        "Low-hanging fruit",
        "pushback",
        "take the lead",
        "value-add",
        "Mac's are better",
        "paradigm",
        "Data Drivin",
        "Win WIn",
        "ROI",
        "Data Driven",
        "Ballpark (estimate)",
        "next gen",
        "phrase 17",
        "phrase 18",
        "phrase 19",
        "phrase 20",
        "phrase 21",
        "phrase 22",
        "phrase 23",
        "phrase 24",
        "phrase 25",
        "phrase 26",
        "phrase 27",
        "phrase 28",
        "phrase 29",
        "phrase 30",
        "phrase 31",
        "phrase 32",
        "phrase 33",
        "phrase 34",
        "phrase 35",
        "phrase 36",
        "phrase 37",
        "phrase 38",
        "phrase 39"
]}